#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use JSON qw();
my $JSON = JSON->new;
my $config_json = do {
	open(my $json_fh, "<:encoding(UTF-8)", "../config/config.json")
		or die("Can't open config.json\": $!\n");
	local $/;
	<$json_fh>
};
our %config = %{ $JSON->decode($config_json) };

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Lang', 'daemon', '-l', 'http://' . $config{"host"} . ':' . $config{"port"});
